spring:
  application:
    name: FastEmail_BE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://47.96.122.101:3306/iqweb
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin123
        reset-enable: false
        url-pattern: /druid/*
      filter:
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
fast:
  email:
    account: excample@qq.com
    password: password
    port: 465
    smtp_host: smtp.mail.qq.com
