spring:
  application:
    name: FastEmail_BE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://47.96.122.101:3306/iqweb
    type: com.alibaba.druid.pool.DruidDataSource